---
abstract: 'Email::Sender with L<Net::SMTP::TLS> (Eg. Gmail)'
author:
  - 'Fayland Lam <fayland@gmail.com>'
generated_by: 'Dist::Zilla version 1.093250'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Sender-Transport-SMTP-TLS
requires:
  Email::Sender: 0.093110
  Net::SMTP::TLS: 0
resources:
  repository: http://github.com/fayland/email-sender-transport-smtp-tls
version: 0.04
